server {
    listen 80;
    server_name armorpltubangka.tech www.armorpltubangka.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name armorpltubangka.tech www.armorpltubangka.tech;

    ssl_certificate /etc/letsencrypt/live/armorpltubangka.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/armorpltubangka.tech/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 50M;

    location /static/ { alias /app/staticfiles/; }
    location /media/  { alias /app/media/; }

    location / {
        proxy_pass         http://localhost:8000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_read_timeout 120;
    }
}

server {
    listen 80;
    server_name simulator.armorpltubangka.tech;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name simulator.armorpltubangka.tech;

    ssl_certificate /etc/letsencrypt/live/simulator.armorpltubangka.tech/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/simulator.armorpltubangka.tech/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    client_max_body_size 20M;

    location / {
        proxy_pass         http://tdc_web:8000;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto https;
        proxy_read_timeout 120;
    }
}
