# Generated by Django 6.0.2 on 2026-02-28 17:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jabatan', models.CharField(blank=True, max_length=100, null=True)),
                ('regu', models.CharField(choices=[('A', 'Regu A'), ('B', 'Regu B'), ('C', 'Regu C'), ('D', 'Regu D'), ('Non-Shift', 'Non-Shift')], default='Non-Shift', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_pekerjaan', models.CharField(max_length=200)),
                ('jenis_pekerjaan', models.CharField(choices=[('FLM', 'First Line Maintenance (FLM)'), ('CM', 'Corrective Maintenance (CM)'), ('PM', 'Preventive Maintenance (PM)')], default='FLM', max_length=3)),
                ('area', models.CharField(choices=[('Boiler', 'Boiler'), ('Turbine', 'Turbine'), ('Coal Handling', 'Coal Handling'), ('Ash Handling', 'Ash Handling'), ('WTP', 'Water Treatment Plant (WTP)'), ('Elektrikal', 'Elektrikal'), ('Lainnya', 'Lainnya')], max_length=20)),
                ('deskripsi', models.TextField()),
                ('waktu_lapor', models.DateTimeField(auto_now_add=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Open', 'Open / Belum Dikerjakan'), ('Progress', 'On Progress'), ('Finish', 'Selesai')], default='Open', max_length=10)),
                ('foto_evidence', models.ImageField(blank=True, null=True, upload_to='evidence_pekerjaan/')),
                ('eksekutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pekerjaan_diselesaikan', to='core.personel')),
            ],
        ),
        migrations.CreateModel(
            name='Absensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField(default=django.utils.timezone.now)),
                ('shift', models.CharField(choices=[('Pagi', 'Pagi'), ('Sore', 'Sore'), ('Malam', 'Malam'), ('Non-Shift', 'Non-Shift')], max_length=10)),
                ('status', models.CharField(choices=[('Hadir', 'Hadir'), ('Izin', 'Izin'), ('Sakit', 'Sakit'), ('Cuti', 'Cuti')], default='Hadir', max_length=10)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personel')),
            ],
        ),
    ]
