# Generated by Django 6.0.5 on 2026-05-19 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerjaan',
            name='foto_evidence',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='evidence_pekerjaan/'),
        ),
    ]
