# Generated by Django 6.0.5 on 2026-05-25 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pekerjaan_foto_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pekerjaan',
            name='area',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='pekerjaan',
            name='jenis_pekerjaan',
            field=models.CharField(default='First Line Maintenance ( A )', max_length=50),
        ),
        migrations.AlterField(
            model_name='pekerjaan',
            name='status',
            field=models.CharField(default='Open', max_length=20),
        ),
        migrations.AlterField(
            model_name='pekerjaan',
            name='waktu_lapor',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
