# Generated by Django 6.0.5 on 2026-05-25 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pekerjaan_area_alter_pekerjaan_jenis_pekerjaan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerjaan',
            name='foto_evidence_after',
            field=models.ImageField(blank=True, max_length=1000, null=True, upload_to='evidence_pekerjaan/'),
        ),
        migrations.AddField(
            model_name='pekerjaan',
            name='nama_peralatan',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pekerjaan',
            name='nomor_sr',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
