# Generated by Django 6.0.5 on 2026-05-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pekerjaan_foto_evidence_after_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerjaan',
            name='nama_pelaksana',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
