# Generated by Django 6.0.5 on 2026-05-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pekerjaan_nama_pelaksana'),
    ]

    operations = [
        migrations.AddField(
            model_name='pekerjaan',
            name='eksekutor_list',
            field=models.ManyToManyField(blank=True, related_name='pekerjaan_diikuti', to='core.personel'),
        ),
    ]
