# Generated by Django 6.0.5 on 2026-05-26 17:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pekerjaan_eksekutor_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ptw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_ptw', models.CharField(max_length=100)),
                ('no_wo', models.CharField(blank=True, default='', max_length=100)),
                ('tanggal_terbit', models.DateField(default=django.utils.timezone.now)),
                ('nama_pekerjaan', models.TextField(blank=True, default='')),
                ('area', models.CharField(blank=True, default='', max_length=100)),
                ('peralatan', models.CharField(blank=True, default='', max_length=200)),
                ('pelaksana', models.CharField(blank=True, default='', max_length=300)),
                ('checklist', models.JSONField(blank=True, default=list)),
                ('keterangan', models.TextField(blank=True, default='')),
                ('bukti_isolasi', models.ImageField(blank=True, max_length=1000, null=True, upload_to='ptw/')),
                ('bukti_release', models.ImageField(blank=True, max_length=1000, null=True, upload_to='ptw/')),
                ('status', models.CharField(default='Open', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'core_ptw',
                'ordering': ['-tanggal_terbit', '-id'],
            },
        ),
    ]
