# Generated by Django 6.0.5 on 2026-05-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_ptw'),
    ]

    operations = [
        migrations.CreateModel(
            name='RTPM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('area', models.CharField(max_length=100)),
                ('tanggal', models.DateField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Done', 'Done'), ('Overdue', 'Overdue')], default='Open', max_length=20)),
                ('pelaksana', models.CharField(blank=True, max_length=100, null=True)),
                ('catatan', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
