# Generated by Django 6.0.5 on 2026-05-26 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rtpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtpm',
            name='minggu_ke',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
