# Generated by Django 6.0.5 on 2026-05-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rtpm_minggu_ke'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtpm',
            name='evidence',
            field=models.ImageField(blank=True, null=True, upload_to='rtpm/'),
        ),
    ]
