# Generated by Django 6.0.5 on 2026-05-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pekerjaan_created_by_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('SOP', 'SOP'), ('MANUAL', 'MANUAL'), ('HISTORY', 'HISTORY')], max_length=20)),
                ('file', models.FileField(upload_to='knowledge/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
