# Generated by Django 6.0.5 on 2026-05-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_knowledgedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgedocument',
            name='file',
            field=models.FileField(max_length=1000, upload_to='knowledge/'),
        ),
        migrations.AlterField(
            model_name='knowledgedocument',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
