# Generated by Django 6.0.5 on 2026-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_knowledgedocument_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgedocument',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
