# Generated by Django 6.0.5 on 2026-05-27 17:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_knowledgedocument_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(blank=True, default='')),
                ('similar_cases', models.JSONField(default=list)),
                ('relevant_ikp', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_ready', models.BooleanField(default=False)),
                ('pekerjaan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendation', to='core.pekerjaan')),
            ],
            options={
                'db_table': 'core_ai_recommendation',
            },
        ),
    ]
