# Generated by Django 6.0.5 on 2026-05-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_airecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='airecommendation',
            name='kemungkinan_penyebab',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='langkah_penanganan',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='llm_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='airecommendation',
            name='perhatian_keselamatan',
            field=models.JSONField(default=list),
        ),
    ]
