# Generated by Django 6.0.5 on 2026-05-29 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_airecommendation_kemungkinan_penyebab_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('produksi', 'Produksi (A/B/C/D)'), ('rendal', 'Rendal'), ('har_listrik', 'Har Listrik'), ('har_mekanik', 'Har Mekanik'), ('har_konin', 'Har Konin')], default='produksi', max_length=20, null=True),
        ),
    ]
